### PR TITLE
Add git repository url to npm page.

### PR DESCRIPTION
**Pull request by AlexKVal**

### CODE REVIEW

**Comment by mtscout6** [comment]
Thanks for the catch, I re-ran `npm init` against the repo witch automatically added a few more things as well.

**Comment by mathieumg** [comment]
I had a tab open to do this at lunchtime and you beat me to it! :tada:

**Comment by mtscout6** [comment]
Sorry guys I realized I missed something and force pushed. I won't do that again on this repo :blush:

**Comment by AlexKVal** [comment]
> I had a tab open to do this at lunchtime and you beat me to it! :tada:

You've been chatting :wink: 
Because you know English well.
And I don't yet. 

Then all I left - is coding :smile:

**Pull request closed without merging**
